name: Build and Deploy as GitHub Page
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install and Build
        run: |
          corepack enable
          corepack prepare
          pnpm install
          env NODE_ENV=production pnpm build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: ./dist
